name: "ZMK Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore: ["README.md", ".github/workflows/draw.yaml"]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
