name: "keymap-drawer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: "caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@9018823e19b572b1c3683e4f91abc8bdc9cac413" # v0.13.2
    with:
      output_folder: "images"
    permissions:
      contents: "write"