name: "keymap-drawer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: "caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@ea00f44ac5a2ebe97b8b31f9166791bedf9136e5" # v0.20.0
    with:
      output_folder: "images"
    permissions:
      contents: "write"