name: "keymap-drawer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: "caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@a44809b8cc718cbff646641f49a8f71a9368336d" # v0.23.0
    with:
      output_folder: "images"
    permissions:
      contents: "write"