name: "keymap-drawer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: "caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@v0.13.2"
    with:
      output_folder: "images"
    permissions:
      contents: "write"